# Generated by Django 4.2.1 on 2023-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userdata_weekly_calorie_goal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BurnedCalories',
            new_name='BurnedCalorie',
        ),
        migrations.RenameModel(
            old_name='Heights',
            new_name='Height',
        ),
        migrations.RenameModel(
            old_name='Weights',
            new_name='Weight',
        ),
        migrations.RenameField(
            model_name='burnedcalorie',
            old_name='user_data_id',
            new_name='user_data',
        ),
        migrations.RenameField(
            model_name='height',
            old_name='user_data_id',
            new_name='user_data',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='user_data_id',
            new_name='user_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture/'),
        ),
    ]
