# Generated by Django 4.2.1 on 2023-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnedcalorie',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='height',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
