# Generated by Django 4.2.1 on 2023-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_burnedcalories_burnedcalorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
