# Generated by Django 4.2.1 on 2023-07-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_burnedcalorie_date_alter_height_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
