# Generated by Django 4.2.1 on 2023-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Users', '0003_alter_user_date_of_birth_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_categories',
            field=models.ManyToManyField(related_name='liked_by', to='Category.category'),
        ),
    ]
