# Generated by Django 4.2.1 on 2023-06-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcategory',
            old_name='user_data_id',
            new_name='user_data',
        ),
    ]
