# Generated by Django 4.2.1 on 2023-06-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_liked_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weekly_calorie_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_category_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_exercise_goal',
        ),
    ]
