# Generated by Django 4.2.1 on 2023-06-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_user_weekly_calorie_goal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='height',
            old_name='user_data',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='user_data',
            new_name='user',
        ),
    ]
