# Generated by Django 4.2.1 on 2023-06-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_user_data_height_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcategory',
            old_name='user_data',
            new_name='user',
        ),
    ]
