# Generated by Django 4.2.1 on 2023-06-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_completedcategory'),
        ('Users', '0007_rename_user_data_completedcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_categories',
            field=models.ManyToManyField(related_name='likes', to='Category.category'),
        ),
        migrations.DeleteModel(
            name='CompletedCategory',
        ),
    ]
