# Generated by Django 4.2.1 on 2023-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('goal', models.IntegerField()),
            ],
            options={
                'ordering': ['-week'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyCategoryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('goal', models.IntegerField()),
            ],
            options={
                'ordering': ['-week'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyExerciseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('goal', models.IntegerField()),
            ],
            options={
                'ordering': ['-week'],
            },
        ),
    ]
