# Generated by Django 4.2.1 on 2023-06-25 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyExerciseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('exercise_goal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exercise_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_date'],
                'unique_together': {('user', 'last_date', 'exercise_goal')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyCategoryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('category_goal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_category_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_date'],
                'unique_together': {('user', 'last_date', 'category_goal')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('calorie_goal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_calorie_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_date'],
                'unique_together': {('user', 'last_date')},
            },
        ),
    ]
