# Generated by Django 4.2.1 on 2023-06-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyexercisegoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exercise_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklycategorygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_category_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklycaloriegoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_calorie_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
