# Generated by Django 4.2.1 on 2023-06-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_alter_weeklyexercisegoal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklycaloriegoal',
            options={'ordering': ['-week']},
        ),
        migrations.AlterModelOptions(
            name='weeklycategorygoal',
            options={'ordering': ['-week']},
        ),
        migrations.RenameField(
            model_name='weeklycaloriegoal',
            old_name='calorie_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='weeklycaloriegoal',
            old_name='last_date',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='weeklycategorygoal',
            old_name='category_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='weeklycategorygoal',
            old_name='last_date',
            new_name='week',
        ),
        migrations.AlterUniqueTogether(
            name='weeklycaloriegoal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklycategorygoal',
            unique_together=set(),
        ),
    ]
