# Generated by Django 4.2.1 on 2023-07-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
