# Generated by Django 4.2.1 on 2023-07-09 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trainer', '0003_alter_certificate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
