# Generated by Django 4.2.1 on 2023-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0004_alter_trainerdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default=1, upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
