# Generated by Django 4.2.1 on 2023-06-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('demo', models.FileField(upload_to='exercise_demos/')),
                ('count', models.PositiveIntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('video_link', models.CharField(blank=True, max_length=250)),
                ('burn_calorie', models.IntegerField()),
                ('focused_area', models.CharField(max_length=250, null=True)),
                ('category', models.ManyToManyField(related_name='exercises', to='Category.category')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='Category.category')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='Exercises.exercise')),
            ],
        ),
    ]
