# Generated by Django 4.2.1 on 2023-06-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
