# Generated by Django 4.2.1 on 2023-06-30 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_completedcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exercises', '0003_exercise_burn_calorie_exercise_focused_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='Category.category')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='Exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
