# Generated by Django 4.2.1 on 2023-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transformation', '0002_transformationimage_delete_transformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformationimage',
            name='date',
        ),
        migrations.AddField(
            model_name='transformationimage',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
